version: '2'
services:
    bd:
        container_name: testenetshow-bd
        build:
            context: .
            dockerfile: Dockerfile-bd
        volumes:
            - ./build/servico:/var/www/html
        image: gcr.io/plasma-amphora-323417/testenetshow-bd
        environment:
            POSTGRES_USER: testenetshow
            POSTGRES_PASSWORD: testenetshow
            POSTGRES_DB: testenetshow
        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        ports:
            - "5434:5432"
        restart: always
    servico:
        container_name: testenetshow-servico
        build:
            context: .
            dockerfile: Dockerfile-servico
        volumes:
            - ./codigo-fonte/servico:/var/www/html
        image: gcr.io/plasma-amphora-323417/testenetshow-servico
        ports:
            - "8080:80"
        restart: always
        links:
            - bd
        depends_on:
            - bd
    cliente:
        container_name: testenetshow-cliente
        build:
            context: .
            dockerfile: Dockerfile-cliente
        volumes:
            - ./codigo-fonte/cliente:/var/www/html
        image: gcr.io/plasma-amphora-323417/testenetshow-cliente

        ports:
            - "80:8080"
        restart: always
        depends_on:
            - servico

            